---
driver:
  name: docker

platforms:

- name: jenkins-master.molecule
  image: "oraclelinux:9"
  command: "/usr/lib/systemd/systemd"
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
  privileged: true
  pre_build_image: true
  cgroupns_mode: host
  groups:
  - jenkins
  docker_networks:
  - name: molecule
  networks:
  - name: molecule

provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      jenkins:
        jenkins_version: 2.492.3-1.1

verifier:
  name: ansible

scenario:
  name: oraclelinux9
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy
