---
- name: Jenkins | Ensure "EnvironmentFile=-/etc/sysconfig/jenkins" is in section "[Service]" in jenkins.service
  ini_file:
    path: /usr/lib/systemd/system/jenkins.service
    section: "Service"
    option: "EnvironmentFile"
    value: "-/etc/sysconfig/jenkins"
    no_extra_spaces: true
    mode: "0644"
  notify: 
    - Systemd daemon reload

- name: Jenkins | Remove environment options, if present from jenkins.service
  ini_file:
    path: /usr/lib/systemd/system/jenkins.service
    section: "Service"
    option: "Environment"
    state: absent
    mode: "0644"
    backup: yes
  notify: 
    - Systemd daemon reload

- name: Jenkins | Template a file to /etc/sysconfig/jenkins
  ansible.builtin.template:
    src: jenkins.env.j2
    dest: /etc/sysconfig/jenkins
    owner: root
    group: root
    mode: '0640'
  notify: 
    - Jenkins restart
    - Systemd daemon reload

- name: Jenkins | Folder for groovy starup scripts
  file:
    path: "/var/lib/jenkins/init.groovy.d"
    owner: jenkins
    group: jenkins
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: Jenkins first start script
  ansible.builtin.copy:
    content: "{{ jenkins_groovy_first_start_script }}"
    dest: /var/lib/jenkins/init.groovy.d/firstStart.groovy
    owner: jenkins
    group: jenkins
    mode: '0750'
  when: jenkins_installed.changed
  notify: 
    - Remove first start script

- name: Jenkins | Ensure service is enabled & started
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: true

- name: Jenkins | Wait for Jenkins to start up
  ansible.builtin.uri:
    url: http://localhost:8080
    status_code: 200
    timeout: 5
  register: _result
  retries: 20
  delay: 5
  until: "'status' in _result and _result['status'] == 200"
