---
- name: Jenkins | Add docker repository
  ansible.builtin.yum_repository:
    name: "docker-ce-stable"
    description: "Docker CE Stable - $basearch"
    baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
    state: "{{ item.state | default('present') }}"
    gpgkey: "https://download.docker.com/linux/centos/gpg"
    gpgcheck: true

- name: Jenkins | Uninstall podman & moby-engine
  ansible.builtin.yum:
    name:
    - podman
    - moby-engine
    state: absent

- name: Jenkins | Install Docker CE
  ansible.builtin.dnf:
    name: 
    - docker-ce 
    - docker-ce-cli  
    - containerd.io

- name: Jenkins | Install python3-docker
  ansible.builtin.dnf:
    name: 
    - python3-docker

- name: Jenkins | Add the user 'jenkins' to group 'docker'
  ansible.builtin.user:
    name: jenkins
    groups: docker
    append: yes
  notify: 
    - Docker restart

- name: Jenkins | Ensure docker service is enabled & started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
