---
- name: "Jenkins | Folder for groovy starup scripts"
  file:
    path: "/var/lib/jenkins/init.groovy.d"
    owner: jenkins
    group: jenkins
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: "Jenkins | Groovy starup script"
  ansible.builtin.copy:
    content: "{{ jenkins_groovy_starup_script }}"
    dest: /var/lib/jenkins/init.groovy.d/seed.groovy
    owner: jenkins
    group: jenkins
    mode: '0750'
  when: jenkins_groovy_starup_script is defined
  notify: 
    - Jenkins restart
