---
- name: Info
  debug:
    msg: 
    - Master url - http://{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}:8080
    - Admin user login - {{ jenkins_admin_user }}
    - Admin user password - {{ jenkins_admin_user_pass }}
