---
- name: Jenkins | Copy Jenkins repo GPG key
  ansible.builtin.copy:
    src: jenkins.io-2023.key
    dest: "/etc/pki/rpm-gpg/jenkins.io-2023.key"
    owner: root
    group: root
    mode: "0644"

- name: Jenkins | Add Jenkins repository
  ansible.builtin.yum_repository:
    name: "jenkins"
    description: "Jenkins-stable"
    baseurl: "{{ jenkins_repo_url }}"
    state: present
    gpgkey: "file:///etc/pki/rpm-gpg/jenkins.io-2023.key"

- name: Jenkins | Install jenkins
  ansible.builtin.yum:
    name: jenkins-{{ jenkins_version }}

- name: Jenkins | Ensure group "jenkins" exists
  ansible.builtin.group:
    name: jenkins
    state: present

- name: Jenkins | Add to user 'jenkins' bash shell
  ansible.builtin.user:
    name: jenkins
    groups: jenkins
    shell: /bin/bash
    append: yes
