---
- name: Install plugins
  community.general.jenkins_plugin:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    url_username: "{{ jenkins_admin_user }}"
    url_password: "{{ jenkins_admin_user_pass }}"
  register: jenkins_plugins_install
  with_items: "{{ jenkins_plugins }}"
  notify: 
    - Jenkins restart
