---
- name: Systemd daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Jenkins restart
  service:
    name: jenkins
    state: restarted

- name: Remove first start script
  file:
    path: /var/lib/jenkins/init.groovy.d/firstStart.groovy
    state: absent
