---
- name: Converge
  hosts: all
  gather_facts: true
  become: no

  tasks:
  
  - name: "Include role"
    ansible.builtin.include_role:
       name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
