---
driver:
  name: docker

platforms:
- &default
  name: jenkins-oraclelinux9.molecule
  image: "oraclelinux:9"
  command: "/usr/lib/systemd/systemd"
  volumes:
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
  privileged: true
  pre_build_image: true
  cgroupns_mode: host
  groups:
  - jenkins

- <<: *default
  name: jenkins-almalinux9.molecule
  image: almalinux:9

provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      jenkins:
        jenkins_java_pkg: java-21-openjdk
        jenkins_port: 8080
        jenkins_admin_user: "admin"
        jenkins_admin_user_pass: "password"
        jenkins_casc_install: true
        jenkins_plugins:
        - name: job-dsl
          version: "1.92"
        - name: workflow-aggregator
        - name: pipeline-stage-view
        - name: git
        - name: git-parameter
        - name: docker-plugin
        - name: script-security

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy
